#!/usr/bin/env python3
"""Generate ThermoFlow CalVer headers (YYYY.WW.REVISION, full 4-digit year)."""

from __future__ import annotations

import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
HEADER_PATH = REPO_ROOT / "include" / "thermoflow_version.h"
CMAKE_PATH = REPO_ROOT / "cmake" / "thermoflow_version.cmake"


def env_int(name: str, default: int) -> int:
    raw = os.environ.get(name, "").strip()
    if not raw:
        return default
    return int(raw)


def env_str(name: str, default: str) -> str:
    raw = os.environ.get(name, "").strip()
    return raw if raw else default


def git_sha() -> str:
    env_sha = os.environ.get("GIT_SHA", "").strip()
    if env_sha:
        return env_sha[:12]

    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short=7", "HEAD"],
            cwd=REPO_ROOT,
            check=True,
            capture_output=True,
            text=True,
        )
        return result.stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def build_timestamp() -> datetime:
    epoch = os.environ.get("SOURCE_DATE_EPOCH", "").strip()
    if epoch.isdigit():
        return datetime.fromtimestamp(int(epoch), tz=timezone.utc)
    return datetime.now(timezone.utc)


def main() -> int:
    now = build_timestamp()
    iso_year, iso_week, _ = now.isocalendar()

    year = env_int("VERSION_YEAR", iso_year)
    week = env_int("VERSION_WEEK", iso_week)
    revision = env_int("REVISION", 1)
    build_number = env_int("BUILD_NUMBER", 0)
    channel = env_str("CHANNEL", "dev")
    git = git_sha()

    version_string = f"{year}.{week}.{revision}"
    if build_number > 0:
        version_full = f"{version_string}+{build_number}"
    else:
        version_full = version_string

    header = f"""/**
 * @file thermoflow_version.h
 * @brief Central firmware version definitions for ThermoFlow
 *
 * Auto-generated by scripts/generate_version.py — do not edit by hand.
 * Scheme: YYYY.WW.REVISION (full 4-digit year, ISO week, revision)
 */

#ifndef THERMOFLOW_VERSION_H
#define THERMOFLOW_VERSION_H

#define THERMOFLOW_VERSION_YEAR       {year}
#define THERMOFLOW_VERSION_WEEK       {week}
#define THERMOFLOW_VERSION_REVISION   {revision}

#define THERMOFLOW_VERSION_STRING     "{version_string}"
#define THERMOFLOW_VERSION_FULL       "{version_full}"

#define THERMOFLOW_BUILD_NUMBER       {build_number}
#define THERMOFLOW_GIT_SHA            "{git}"
#define THERMOFLOW_CHANNEL            "{channel}"

/** Security version for OTA anti-rollback */
#define THERMOFLOW_SECURITY_VERSION 1

#endif /* THERMOFLOW_VERSION_H */
"""

    cmake = f"""# Auto-generated by scripts/generate_version.py — do not edit by hand.
set(THERMOFLOW_PROJECT_VER "{version_string}")
"""

    HEADER_PATH.parent.mkdir(parents=True, exist_ok=True)
    CMAKE_PATH.parent.mkdir(parents=True, exist_ok=True)
    HEADER_PATH.write_text(header, encoding="utf-8", newline="\n")
    CMAKE_PATH.write_text(cmake, encoding="utf-8", newline="\n")

    print(
        f"Generated ThermoFlow version {version_full} "
        f"(channel={channel}, sha={git})"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())