#!/usr/bin/env python3
"""Generate ThermoFlow version headers.

Pre-release (default): YYYY.WW.BUILD — full year, ISO week, CI build number.
Release: set USE_BUILD_VERSION=0 for YYYY.WW.REVISION (manual revision).

Local builds: fetch latest GitHub Actions run number when BUILD_NUMBER is unset,
and append git SHA to version_full (e.g. 2026.29.37+bb8802f) for uniqueness.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
HEADER_PATH = REPO_ROOT / "include" / "thermoflow_version.h"
CMAKE_PATH = REPO_ROOT / "cmake" / "thermoflow_version.cmake"
DEFAULT_GITHUB_REPO = "itoaa/ThermoFlow"


def env_int(name: str, default: int) -> int:
    raw = os.environ.get(name, "").strip()
    if not raw:
        return default
    return int(raw)


def env_int_optional(name: str) -> int | None:
    raw = os.environ.get(name, "").strip()
    if not raw:
        return None
    return int(raw)


def env_str(name: str, default: str) -> str:
    raw = os.environ.get(name, "").strip()
    return raw if raw else default


def env_bool(name: str, default: bool) -> bool:
    raw = os.environ.get(name, "").strip().lower()
    if not raw:
        return default
    return raw not in ("0", "false", "no", "off")


def git_sha() -> str:
    env_sha = os.environ.get("GIT_SHA", "").strip()
    if env_sha:
        return env_sha[:12]

    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short=7", "HEAD"],
            cwd=REPO_ROOT,
            check=True,
            capture_output=True,
            text=True,
        )
        return result.stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def fetch_latest_github_run_number() -> int | None:
    repo = env_str("GITHUB_REPOSITORY", DEFAULT_GITHUB_REPO)
    url = f"https://api.github.com/repos/{repo}/actions/runs?per_page=1"
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "ThermoFlow-version-generator",
    }
    token = os.environ.get("GITHUB_TOKEN", "").strip()
    if token:
        headers["Authorization"] = f"Bearer {token}"

    request = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(request, timeout=8) as response:
            payload = json.load(response)
    except (urllib.error.URLError, urllib.error.HTTPError, TimeoutError, json.JSONDecodeError):
        return None

    runs = payload.get("workflow_runs") or []
    if not runs:
        return None

    run_number = runs[0].get("run_number")
    if isinstance(run_number, int) and run_number > 0:
        return run_number
    return None


def resolve_build_number() -> tuple[int, str]:
    explicit = env_int_optional("BUILD_NUMBER")
    if explicit is not None:
        return explicit, "env"

    if os.environ.get("GITHUB_ACTIONS") == "true":
        run_number = env_int_optional("GITHUB_RUN_NUMBER")
        if run_number is not None:
            return run_number, "github_actions"
        return 0, "github_actions_fallback"

    if env_bool("FETCH_GITHUB_BUILD", True):
        fetched = fetch_latest_github_run_number()
        if fetched is not None:
            return fetched, "github_api"

    return 0, "local_fallback"


def build_timestamp() -> datetime:
    epoch = os.environ.get("SOURCE_DATE_EPOCH", "").strip()
    if epoch.isdigit():
        return datetime.fromtimestamp(int(epoch), tz=timezone.utc)
    return datetime.now(timezone.utc)


def main() -> int:
    now = build_timestamp()
    iso_year, iso_week, _ = now.isocalendar()

    year = env_int("VERSION_YEAR", iso_year)
    week = env_int("VERSION_WEEK", iso_week)
    revision = env_int("REVISION", 1)
    build_number, build_source = resolve_build_number()
    channel = env_str("CHANNEL", "dev")
    git = git_sha()
    use_build_version = env_bool("USE_BUILD_VERSION", True)
    is_ci = os.environ.get("GITHUB_ACTIONS") == "true"
    local_build = env_bool("LOCAL_BUILD", not is_ci)

    if use_build_version:
        version_scheme = "build"
        third = build_number
        version_string = f"{year}.{week}.{third}"
        release_calver = f"{year}.{week}.{revision}"
    else:
        version_scheme = "revision"
        third = revision
        version_string = f"{year}.{week}.{revision}"
        release_calver = version_string

    if local_build and git != "unknown":
        version_full = f"{version_string}+{git}"
    else:
        version_full = version_string

    header = f"""/**
 * @file thermoflow_version.h
 * @brief Central firmware version definitions for ThermoFlow
 *
 * Auto-generated by scripts/generate_version.py — do not edit by hand.
 * Pre-release: YYYY.WW.BUILD (USE_BUILD_VERSION=1).
 * Release: YYYY.WW.REVISION with USE_BUILD_VERSION=0.
 */

#ifndef THERMOFLOW_VERSION_H
#define THERMOFLOW_VERSION_H

#define THERMOFLOW_VERSION_YEAR       {year}
#define THERMOFLOW_VERSION_WEEK       {week}
#define THERMOFLOW_VERSION_REVISION   {third}

#define THERMOFLOW_CALVER_STRING      "{release_calver}"
#define THERMOFLOW_VERSION_SCHEME     "{version_scheme}"

#define THERMOFLOW_VERSION_STRING     "{version_string}"
#define THERMOFLOW_VERSION_FULL       "{version_full}"

#define THERMOFLOW_BUILD_NUMBER       {build_number}
#define THERMOFLOW_GIT_SHA            "{git}"
#define THERMOFLOW_CHANNEL            "{channel}"

/** Security version for OTA anti-rollback */
#define THERMOFLOW_SECURITY_VERSION 1

#endif /* THERMOFLOW_VERSION_H */
"""

    cmake = f"""# Auto-generated by scripts/generate_version.py — do not edit by hand.
set(THERMOFLOW_PROJECT_VER "{version_string}")
"""

    HEADER_PATH.parent.mkdir(parents=True, exist_ok=True)
    CMAKE_PATH.parent.mkdir(parents=True, exist_ok=True)
    HEADER_PATH.write_text(header, encoding="utf-8", newline="\n")
    CMAKE_PATH.write_text(cmake, encoding="utf-8", newline="\n")

    print(
        f"Generated ThermoFlow version {version_full} "
        f"(scheme={version_scheme}, build={build_number} via {build_source}, "
        f"channel={channel}, sha={git})"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())