/**
 * @file thermoflow_version.h
 * @brief Central firmware version definitions for ThermoFlow
 *
 * Auto-generated by scripts/generate_version.py — do not edit by hand.
 * Scheme: YYYY.WW.REVISION (full 4-digit year, ISO week, revision)
 */

#ifndef THERMOFLOW_VERSION_H
#define THERMOFLOW_VERSION_H

#define THERMOFLOW_VERSION_YEAR       2026
#define THERMOFLOW_VERSION_WEEK       29
#define THERMOFLOW_VERSION_REVISION   1

#define THERMOFLOW_VERSION_STRING     "2026.29.1"
#define THERMOFLOW_VERSION_FULL       "2026.29.1"

#define THERMOFLOW_BUILD_NUMBER       0
#define THERMOFLOW_GIT_SHA            "unknown"
#define THERMOFLOW_CHANNEL            "dev"

/** Security version for OTA anti-rollback */
#define THERMOFLOW_SECURITY_VERSION 1

#endif /* THERMOFLOW_VERSION_H */