/**
 * @file thermoflow_version.h
 * @brief Central firmware version definitions for ThermoFlow
 *
 * Auto-generated by scripts/generate_version.py — do not edit by hand.
 * Pre-release: BUILD_NUMBER as user-facing version (USE_BUILD_VERSION=1).
 * Release: CalVer YYYY.WW.REVISION with USE_BUILD_VERSION=0.
 */

#ifndef THERMOFLOW_VERSION_H
#define THERMOFLOW_VERSION_H

#define THERMOFLOW_VERSION_YEAR       2026
#define THERMOFLOW_VERSION_WEEK       29
#define THERMOFLOW_VERSION_REVISION   1

#define THERMOFLOW_CALVER_STRING      "2026.29.1"
#define THERMOFLOW_VERSION_SCHEME     "build"

#define THERMOFLOW_VERSION_STRING     "dev"
#define THERMOFLOW_VERSION_FULL       "dev"

#define THERMOFLOW_BUILD_NUMBER       0
#define THERMOFLOW_GIT_SHA            "d208a3f"
#define THERMOFLOW_CHANNEL            "dev"

/** Security version for OTA anti-rollback */
#define THERMOFLOW_SECURITY_VERSION 1

#endif /* THERMOFLOW_VERSION_H */
