/**
 * @file thermoflow_version.h
 * @brief Central firmware version definitions for ThermoFlow
 *
 * Auto-generated by scripts/generate_version.py — do not edit by hand.
 * Pre-release: YYYY.WW.BUILD (USE_BUILD_VERSION=1).
 * Release: YYYY.WW.REVISION with USE_BUILD_VERSION=0.
 */

#ifndef THERMOFLOW_VERSION_H
#define THERMOFLOW_VERSION_H

#define THERMOFLOW_VERSION_YEAR       2026
#define THERMOFLOW_VERSION_WEEK       29
#define THERMOFLOW_VERSION_REVISION   48

#define THERMOFLOW_CALVER_STRING      "2026.29.1"
#define THERMOFLOW_VERSION_SCHEME     "build"

#define THERMOFLOW_VERSION_STRING     "2026.29.48"
#define THERMOFLOW_VERSION_FULL       "2026.29.48+cba6fa2"

#define THERMOFLOW_BUILD_NUMBER       48
#define THERMOFLOW_GIT_SHA            "cba6fa2"
#define THERMOFLOW_CHANNEL            "dev"

/** Security version for OTA anti-rollback */
#define THERMOFLOW_SECURITY_VERSION 1

#endif /* THERMOFLOW_VERSION_H */
